version: "3.7"
services: 

    chat-db:
        image: postgres:11-alpine
        ports:
            - 5432:5432
        volumes:
            - chat-database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
        environment:
            POSTGRES_USER: "chatdb"
            POSTGRES_PASSWORD: "chatdb"
            POSTGRES_DB: "chatdb"

volumes: 
    chat-database-data: