version: "3.7"
services: 

    chat-api-service:
        image: chat-api-service:latest
        build: .
        container_name: chat-api-service
        ports: 
            - 8080:8080
        environment: 
            - PORT="8080"
            - HOST="0.0.0.0"
